name: Update README

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: |
          curl -o README.md https://raw.githubusercontent.com/Shuaib-ux/portfolio/main/README.md
      - name: Commit changes
        run: |
          git config --global user.name 'shuaib-ux'
          git config --global user.email 'shuaibakoh6@gmail.com'
          git add README.md
          git commit -m 'Updated README'
          git push
