name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "# Shuaib Idoko-Akoh's Portfolio" > README.md
          echo "## A passionate frontend developer from Nigeria" >> README.md
          echo "![Profile views](https://komarev.com/ghpvc/?username=Shuaib-ux&label=Profile%20views&color=0e75b6&style=flat)" >> README.md
          echo "[![Follow on GitHub](https://img.shields.io/github/followers/Shuaib-ux?label=Follow&style=social)](https://github.com/Shuaib-ux)" >> README.md
          echo "- 🔭 I’m currently working on [WAY Services Ltd](#)" >> README.md
          echo "- 🌱 I’m currently learning **everything**" >> README.md
          echo "- 👯 I’m looking to collaborate on **bizarre ideas**" >> README.md
          echo "- 📫 How to reach me **Shuaibakoh6@gmail.com**" >> README.md
          echo "- ⚡ Fun fact **I love travelling and learning people cultures**" >> README.md
          echo "## Connect with me:" >> README.md
          echo "[![Twitter](https://img.shields.io/badge/Twitter-1DA1F2?logo=twitter&logoColor=white)](https://twitter.com/your_handle)" >> README.md
          echo "[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?logo=linkedin&logoColor=white)](https://linkedin.com/in/shuaib-i-ab882bb6)" >> README.md
          echo "[![GitHub](https://img.shields.io/badge/GitHub-181717?logo=github&logoColor=white)](https://github.com/Shuaib-ux)" >> README.md
          echo "## Languages and Tools:" >> README.md
          echo "![JavaScript](https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E)" >> README.md
          echo "![TypeScript](https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white)" >> README.md
          echo "![React](https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB)" >> README.md
          echo "![Next.js](https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=nextdotjs&logoColor=white)" >> README.md
          echo "![Vite](https://img.shields.io/badge/Vite-646CFF?style=for-the-badge&logo=vite&logoColor=white)" >> README.md
          echo "![Tailwind CSS](https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=for-the-badge&logo=tailwind-css&logoColor=white)" >> README.md
          echo "![Chakra UI](https://img.shields.io/badge/Chakra_UI-319795?style=for-the-badge&logo=chakra-ui&logoColor=white)" >> README.md
          echo "![Node.js](https://img.shields.io/badge/Node.js-43853D?style=for-the-badge&logo=node.js&logoColor=white)" >> README.md
          echo "![MongoDB](https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white)" >> README.md
          echo "![Git](https://img.shields.io/badge/Git-F05032?style=for-the-badge&logo=git&logoColor=white)" >> README.md
          echo "## GitHub Stats" >> README.md
          echo "![Shuaib's GitHub stats](https://github-readme-stats.vercel.app/api?username=Shuaib-ux&show_icons=true&theme=radical&count_private=true&hide=contribs,issues&token=${{ secrets.GH_TOKEN }})" >> README.md
          echo "## Top Languages" >> README.md
          echo "![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Shuaib-ux&layout=compact&theme=radical&langs_count=8&hide=python&count_private=true&token=${{ secrets.GH_TOKEN }})" >> README.md
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m 'Updated README'
          git push
